# Generated by Django 2.0.9 on 2019-06-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('singer', models.CharField(blank=True, max_length=255, null=True)),
                ('song_name', models.CharField(blank=True, max_length=255, null=True)),
                ('msg_count', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('notif_sender', models.CharField(blank=True, max_length=255, null=True)),
                ('notif_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('default_phone_number', models.CharField(blank=True, max_length=255, null=True)),
                ('hint_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('incoming_call_number', models.CharField(blank=True, max_length=255, null=True)),
                ('incoming_call_name', models.CharField(blank=True, max_length=255, null=True)),
                ('clipboard_msg', models.CharField(blank=True, max_length=255, null=True)),
                ('second_name', models.CharField(blank=True, max_length=255, null=True)),
                ('second_text', models.CharField(blank=True, max_length=255, null=True)),
                ('hint_1', models.CharField(blank=True, max_length=255, null=True)),
                ('hint_2', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(choices=[('PIN', '0'), ('PASSWORD', '1')], default='0', max_length=1)),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('cover', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('incoming_call_image', models.ImageField(blank=True, max_length=255, null=True, upload_to='')),
                ('hint_count', models.IntegerField(blank=True, default=0, null=True)),
                ('pin_count', models.IntegerField(blank=True, default=4, null=True)),
                ('index', models.IntegerField(blank=True, default=4, null=True)),
                ('notif', models.BooleanField(default=False)),
                ('hint', models.BooleanField(default=False)),
                ('passed', models.BooleanField(default=False)),
                ('incoming_call', models.BooleanField(default=False)),
                ('clipboard', models.BooleanField(default=False)),
                ('second_notif', models.BooleanField(default=False)),
            ],
        ),
    ]
