# Generated by Django 2.1.7 on 2019-06-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='type',
            field=models.CharField(choices=[('0', 'PING'), ('1', 'PASSWORD')], default='0', max_length=1),
        ),
    ]
