# Generated by Django 2.1.7 on 2019-07-16 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0003_auto_20190701_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='contact_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='level',
            name='contact_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
