# Generated by Django 2.1.7 on 2019-08-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0004_auto_20190716_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
            ],
        ),
    ]
