# Generated by Django 2.1.7 on 2019-10-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('level', '0008_auto_20191004_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levelpackage',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=''),
        ),
    ]
